@node
@dataset=peshitta
@datasetName=Peshitta
@description=?
@email1=dirk.roorda@dans.knaw.nl
@encoders=Eep Talstra Centre for Bible and Computer. LinkSyr project (CLARIAH research pilot). Hannes Vlaardingerbroek, Constantijn Sikkel (PIL) and Dirk Roorda (TF)
@language=English
@languageCode=en
@languageEnglish=English
@source=SEDRA
@sourceUrl=https://sedra.bethmardutho.org/about/contributors
@valueType=str
@writtenBy=Text-Fabric
@dateWritten=2018-10-16T05:44:46Z

426164	Genesis
Exodus
Leviticus
Numbers
Deuteronomy
Job
Joshua
Judges
1Samuel
2Samuel
Psalms
1Kings
2Kings
Proverbs
Wisdom_of_Solomon
Ecclesiastes
Song_of_Songs
Isaiah
Jeremiah
Lamentations
Letter_of_Jeremiah
Letter_of_Baruch_A
Letter_of_Baruch_B
Baruch
Ezekiel
Hosea
Joel
Amos
Obadiah
Jonah
Micah
Nahum
Habakkuk
Zephaniah
Haggai
Zechariah
Malachi
Daniel
Bel_and_the_Dragon
Ruth
Susanna
Esther
Judith
Sirach
1Chronicles
2Chronicles
Apocalypse_of_Baruch
4Esdras
Ezra
Nehemia
1Maccabees_A
1Maccabees_B
2Maccabees
3Maccabees
4Maccabees
Odes
Prayer_of_Manasseh_A
Prayer_of_Manasseh_B
Apocryphal_Psalms_A
Apocryphal_Psalms_B
Apocryphal_Psalms
Psalms_of_Solomon
Tobit_A
Tobit_B
3Esdras
